CREATE  TABLE "CATS" (
	"ID" NUMBER(10, 0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(50) NOT NULL ENABLE, 
	"BREED" VARCHAR2(50) NOT NULL ENABLE, 
	"SEX" VARCHAR2(50) NOT NULL ENABLE,
	"AGE" NUMBER(10, 0) NOT NULL ENABLE,
	"COLOUR" VARCHAR2(50) NOT NULL ENABLE,
	CONSTRAINT "CATS_ID_PK" PRIMARY KEY ("ID") ENABLE)
  
  drop table cats;
  INSERT INTO cats (ID,NAME,BREED,SEX,AGE,COLOUR) values (1,'Kitty','Mixed','female',2,'orange/white');
  
  